dataset: fmnist
model: lenet
method: ivon
epochs: 100
batch_size: 128
eval_batch_size: 256
learning_rate: 0.2
lr_final: 0.0
weight_decay: 2e-3
warmup_epochs: 5
random_seed: 0
data_dir: data
output_dir: outputs/fmnist_lenet/ivon/seed0
evaluation: {indomain: true, ood: true, ood_dataset: emnist}
method_hparams: {beta1: 0.9, beta2: 0.99999, hess_init: 0.5, hess_approx: price, ess: 50000.0, mc_samples: 1, test_repeat: 64, rescale_lr: true}
