dataset: fmnist
model: lenet
method: laplace
epochs: 200
batch_size: 512
eval_batch_size: 512
learning_rate: 0.05
lr_final: 0.0
weight_decay: 0.0001
warmup_epochs: 5
random_seed: 0
data_dir: data
output_dir: outputs/fmnist_lenet/laplace/seed0
evaluation: {indomain: true, ood: true, ood_dataset: emnist}
method_hparams: {momentum: 0.9, subset_of_weights: last_layer, hessian_structure: kron, pred_type: glm, link_approx: probit, prior_precision: 1.0, optimize_prior_precision: true}
