dataset: fmnist
model: lenet
method: swag
epochs: 100
batch_size: 128
eval_batch_size: 256
learning_rate: 5e-3
lr_final: 0.0
weight_decay: 1e-5
warmup_epochs: 5
random_seed: 0
data_dir: data
output_dir: outputs/fmnist_lenet/swag/seed0
evaluation: {indomain: true, ood: true, ood_dataset: emnist}
method_hparams: {momentum: 0.9, max_rank: 20, swag_start: 160, swag_freq: 1, model_samples: 64, sample_mode: modelwise}
