optimizer: lcbopt_adaptcurv
dataset: fmnist
model: lenet
seeds: [0, 1, 2]
device: cuda

traindir: "final/lcbopt_adaptcurv/fmnist_lenet/lr_2e-3_wd_2e-3_h0_0.1_gamma_1.02_b3_0.999_ep_100"

train_args:
  lr: "2e-3"
  e: "100"
  weight-decay: "2e-3"
  hess_init: "0.1"
  gamma: "1.02"
  beta1: "0.9"
  beta2: "0.99999"
  beta3: "0.999"
  eps: "1e-8"
  clip-radius: "inf"
  tvsplit: "0.9"
  tbatch: "128"
  vbatch: "256"
  j: "1"

train_flags: []

seed_start: 0
seed_end: 2
eval_subdir: "eval_final"

test_args:
  tvsplit: "1.0"
  batch: "256"
  j: "0"
  checkpoint: "latest"

test_flags:
  - pd
