optimizer: swag
dataset: cifar100
model: densenet121_swag
seeds: [0, 1, 2]
device: cuda

traindir: "final/swag/cifar100_densenet121/lr_5e-2_wd_2e-4"

train_args:
  lr: "5e-2"
  lr_final: "1e-2"
  e: "200"
  weight-decay: "2e-4"
  beta1: "0.9"
  swag_start: "160"
  swag_freq: "1"
  warmup: "0"
  tbatch: "128"
  vbatch: "256"
  tvsplit: "0.9"
  j: "1"

train_flags: []

seed_start: 0
seed_end: 2
eval_subdir: "eval"

test_args:
  tvsplit: "1.0"
  batch: "256"
  j: "0"
  tr: "64"
  checkpoint: "best"

test_flags:
  - pd
