optimizer: swag
dataset: fmnist
model: lenet_swag
seeds: [0, 1, 2]
device: cuda

traindir: "final/swag/fmnist_lenet/lr_5e-3_wd_1e-5"

train_args:
  lr: "5e-3"
  lr_final: "1e-3"
  e: "100"
  weight-decay: "1e-5"
  beta1: "0.9"
  swag_start: "60"
  swag_freq: "1"
  warmup: "0"
  tbatch: "128"
  vbatch: "256"
  tvsplit: "0.9"
  j: "1"

train_flags: []

seed_start: 0
seed_end: 2
eval_subdir: "eval_final"

test_args:
  tvsplit: "1.0"
  batch: "256"
  j: "0"
  tr: "64"
  checkpoint: "latest"

test_flags:
  - pd
